[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "torchberty"
author = "Johny Jose"
author-email = "johnymephisto@gmail.com"
home-page = "https://github.com/johnymephisto"
classifiers = ["License :: OSI Approved :: MIT License"]

